---
# tasks file for setup-reposerver

# required packages
- name: ensure required packages are installed
  package:
          state: present
          name: "{{ item }}"
  with_items:
          - httpd
          - createrepo
          - yum-utils

- name: ensure repository directories exist
  file:
          path: "{{ item }}"
          owner: root
          group: root
          mode: 0755
          setype: httpd_sys_content_t
          state: directory
  with_items:
          - /var/www/html/repofiles
          - /var/www/html/repos

- name: ensure Webserver is enabled & running
  service:
          name: httpd
          state: started
          enabled: yes

- name: ensure firewalld ports for http and https are open
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
          - http
          - https
          
- name: ensure syncrepo script  is installed
  template:
          src: syncrepo.j2
          dest: /usr/sbin/syncrepo.sh
          mode: 0755
  notify: initial_reposync

- name: ensure Reposync Cron is installed
  file:
          src: /usr/sbin/syncrepo.sh
          dest: /etc/cron.{{ reposync_cron }}/syncrepo.sh
          state: link
  when: ( reposync_cron is defined ) and ((reposync_cron == 'daily' ) or ( reposync_cron == 'monthly' ))
